# This script depends on two environment variables to be set in Bitbucket Pipelines
# 1. $HEROKU_API_KEY - Local environment var that contains your Heroku account's API key
# 2. $HEROKU_PRODUCTION - Local environment var that contains your production app name in Heroku

 image: node:16.13.2

 # Doing a full clone to be able to push back to Heroku.
 clone:
   depth: full

 pipelines:
   branches:
     master:
       - step:
           deployment: production
           caches:
             - node
           script:
             - npm install
             - npm run build
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git master
     release/npm:
       - step:
           deployment: production
           caches:
             - node
           script:
             - npm install
             - npm run build
             - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
             - npm publish
     release/github:
       - step:
           deployment: production
           caches:
             - node
           script:
             - git remote add origin git@github.com:cyber-rom/rupor-ui.git
             - git pull --ff-only
             - git push origin main